# SPDX-FileCopyrightText: 2026 Leitwolf <xs-lang.chess031@slmails.com>
# SPDX-License-Identifier: Apache-2.0

[advisories]
ignore = []
informational_warnings = ["unmaintained"]
severity_threshold = "low"

[database]
path = "~/.cargo/advisory-db"
url = "https://github.com/RustSec/advisory-db.git"
fetch = true
stale = false

[output]
format = "terminal"
quiet = false
show_tree = true
deny = []

[yanked]
enabled = true
update_index = true
