/*
 * SPDX-FileCopyrightText: 2026 Leitwolf <xs-lang.chess031@slmails.com>
 * SPDX-License-Identifier: Apache-2.0
 */

#include "xs/token.h"

#include <string.h>

typedef struct
{
  const char *text;
  XsTokenKind kind;
} Keyword;

static const Keyword keywords[] = {
    {"as", XS_TOKEN_KW_AS},
    {"async", XS_TOKEN_KW_ASYNC},
    {"Atomic", XS_TOKEN_KW_ATOMIC},
    {"await", XS_TOKEN_KW_AWAIT},
    {"break", XS_TOKEN_KW_BREAK},
    {"class", XS_TOKEN_KW_CLASS},
    {"const", XS_TOKEN_KW_CONST},
    {"continue", XS_TOKEN_KW_CONTINUE},
    {"data", XS_TOKEN_KW_DATA},
    {"do", XS_TOKEN_KW_DO},
    {"else", XS_TOKEN_KW_ELSE},
    {"enum", XS_TOKEN_KW_ENUM},
    {"extends", XS_TOKEN_KW_EXTENDS},
    {"extern", XS_TOKEN_KW_EXTERN},
    {"false", XS_TOKEN_KW_FALSE},
    {"fn", XS_TOKEN_KW_FN},
    {"for", XS_TOKEN_KW_FOR},
    {"getter", XS_TOKEN_KW_GETTER},
    {"if", XS_TOKEN_KW_IF},
    {"implements", XS_TOKEN_KW_IMPLEMENTS},
    {"imports", XS_TOKEN_KW_IMPORTS},
    {"in", XS_TOKEN_KW_IN},
    {"incomplete", XS_TOKEN_KW_INCOMPLETE},
    {"interface", XS_TOKEN_KW_INTERFACE},
    {"internal", XS_TOKEN_KW_INTERNAL},
    {"macro_rules", XS_TOKEN_KW_MACRO_RULES},
    {"match", XS_TOKEN_KW_MATCH},
    {"module", XS_TOKEN_KW_MODULE},
    {"move", XS_TOKEN_KW_MOVE},
    {"mut", XS_TOKEN_KW_MUT},
    {"namespace", XS_TOKEN_KW_NAMESPACE},
    {"new", XS_TOKEN_KW_NEW},
    {"None", XS_TOKEN_KW_NONE},
    {"op", XS_TOKEN_KW_OP},
    {"private", XS_TOKEN_KW_PRIVATE},
    {"protected", XS_TOKEN_KW_PROTECTED},
    {"public", XS_TOKEN_KW_PUBLIC},
    {"return", XS_TOKEN_KW_RETURN},
    {"setter", XS_TOKEN_KW_SETTER},
    {"static", XS_TOKEN_KW_STATIC},
    {"true", XS_TOKEN_KW_TRUE},
    {"using", XS_TOKEN_KW_USING},
    {"val", XS_TOKEN_KW_VAL},
    {"while", XS_TOKEN_KW_WHILE},
    {"virtual", XS_TOKEN_KW_VIRTUAL},
    {"override", XS_TOKEN_KW_OVERRIDE},
    {"sealed", XS_TOKEN_KW_SEALED},
};

XsTokenKind xs_token_keyword(const char *text, size_t length)
{
  for(size_t i = 0; i < sizeof(keywords) / sizeof(keywords[0]); ++i)
  {
    if(strlen(keywords[i].text) == length && memcmp(keywords[i].text, text, length) == 0)
      return keywords[i].kind;
  }
  return XS_TOKEN_IDENTIFIER;
}

const char *xs_token_kind_name(XsTokenKind kind)
{
  static const char *const names[] = {
      "end of file",
      "invalid token",
      "identifier",
      "integer",
      "float",
      "string",
      "character",
      "lifetime",
      "document comment",
      "module comment",
      "(",
      ")",
      "{",
      "}",
      "[",
      "]",
      ",",
      ";",
      ":",
      "::",
      ":=",
      ".",
      "...",
      "->",
      "=",
      "==",
      "!",
      "!=",
      "?",
      "?.",
      "??",
      ("?"
       "?="),
      ">",
      ">=",
      ">>",
      "<",
      "<=",
      "<<",
      "+",
      "++",
      "+=",
      "-",
      "--",
      "-=",
      "*",
      "*=",
      "/",
      "/=",
      "%",
      "%=",
      "&",
      "&&",
      "&=",
      "|",
      "||",
      "|=",
      "^",
      "^=",
      "#",
      "@",
      "$",
      "as",
      "async",
      "Atomic",
      "await",
      "break",
      "class",
      "const",
      "continue",
      "data",
      "else",
      "enum",
      "extends",
      "extern",
      "fn",
      "for",
      "getter",
      "if",
      "implements",
      "imports",
      "in",
      "incomplete",
      "interface",
      "internal",
      "macro_rules",
      "match",
      "module",
      "move",
      "mut",
      "namespace",
      "new",
      "None",
      "op",
      "private",
      "protected",
      "public",
      "return",
      "setter",
      "static",
      "true",
      "false",
      "using",
      "val",
      "while",
      "virtual",
      "override",
      "sealed",
      "do",
  };
  if((size_t)kind >= sizeof(names) / sizeof(names[0]))
    return "unknown token";
  return names[kind];
}
