#include "xs/token.h"

#include <string.h>

typedef struct
{
  const char *text;
  XsTokenKind kind;
} Keyword;

static const Keyword keywords[] = {
    {"as", XS_TOKEN_KW_AS},
    {"async", XS_TOKEN_KW_ASYNC},
    {"Atomic", XS_TOKEN_KW_ATOMIC},
    {"await", XS_TOKEN_KW_AWAIT},
    {"break", XS_TOKEN_KW_BREAK},
    {"catch", XS_TOKEN_KW_CATCH},
    {"class", XS_TOKEN_KW_CLASS},
    {"const", XS_TOKEN_KW_CONST},
    {"continue", XS_TOKEN_KW_CONTINUE},
    {"data", XS_TOKEN_KW_DATA},
    {"else", XS_TOKEN_KW_ELSE},
    {"enum", XS_TOKEN_KW_ENUM},
    {"extends", XS_TOKEN_KW_EXTENDS},
    {"false", XS_TOKEN_KW_FALSE},
    {"finally", XS_TOKEN_KW_FINALLY},
    {"fn", XS_TOKEN_KW_FN},
    {"for", XS_TOKEN_KW_FOR},
    {"from", XS_TOKEN_KW_FROM},
    {"get", XS_TOKEN_KW_GET},
    {"if", XS_TOKEN_KW_IF},
    {"implements", XS_TOKEN_KW_IMPLEMENTS},
    {"imports", XS_TOKEN_KW_IMPORTS},
    {"in", XS_TOKEN_KW_IN},
    {"incomplete", XS_TOKEN_KW_INCOMPLETE},
    {"interface", XS_TOKEN_KW_INTERFACE},
    {"internal", XS_TOKEN_KW_INTERNAL},
    {"macroRules", XS_TOKEN_KW_MACRO_RULES},
    {"match", XS_TOKEN_KW_MATCH},
    {"module", XS_TOKEN_KW_MODULE},
    {"move", XS_TOKEN_KW_MOVE},
    {"mut", XS_TOKEN_KW_MUT},
    {"namespace", XS_TOKEN_KW_NAMESPACE},
    {"new", XS_TOKEN_KW_NEW},
    {"nil", XS_TOKEN_KW_NIL},
    {"private", XS_TOKEN_KW_PRIVATE},
    {"protected", XS_TOKEN_KW_PROTECTED},
    {"public", XS_TOKEN_KW_PUBLIC},
    {"return", XS_TOKEN_KW_RETURN},
    {"set", XS_TOKEN_KW_SET},
    {"static", XS_TOKEN_KW_STATIC},
    {"throw", XS_TOKEN_KW_THROW},
    {"throws", XS_TOKEN_KW_THROWS},
    {"true", XS_TOKEN_KW_TRUE},
    {"try", XS_TOKEN_KW_TRY},
    {"val", XS_TOKEN_KW_VAL},
    {"while", XS_TOKEN_KW_WHILE},
};

XsTokenKind xs_token_keyword(const char *text, size_t length)
{
  for (size_t i = 0; i < sizeof(keywords) / sizeof(keywords[0]); ++i)
  {
    if (strlen(keywords[i].text) == length && memcmp(keywords[i].text, text, length) == 0)
      return keywords[i].kind;
  }
  return XS_TOKEN_IDENTIFIER;
}

const char *xs_token_kind_name(XsTokenKind kind)
{
  static const char *const names[] = {
      "end of file",
      "invalid token",
      "identifier",
      "integer",
      "float",
      "string",
      "character",
      "lifetime",
      "document comment",
      "module comment",
      "(",
      ")",
      "{",
      "}",
      "[",
      "]",
      ",",
      ";",
      ":",
      ".",
      "...",
      "->",
      "=>",
      "=",
      "==",
      "!",
      "!=",
      ">",
      ">=",
      ">>",
      ">>>",
      "<",
      "<=",
      "<<",
      "<<<",
      "+",
      "++",
      "+=",
      "-",
      "--",
      "-=",
      "*",
      "*=",
      "/",
      "/=",
      "%",
      "%=",
      "&",
      "&&",
      "&=",
      "|",
      "||",
      "|=",
      "$",
      "as",
      "async",
      "Atomic",
      "await",
      "break",
      "catch",
      "class",
      "const",
      "continue",
      "data",
      "else",
      "enum",
      "extends",
      "finally",
      "fn",
      "for",
      "from",
      "get",
      "if",
      "implements",
      "imports",
      "in",
      "incomplete",
      "interface",
      "internal",
      "macroRules",
      "match",
      "module",
      "move",
      "mut",
      "namespace",
      "new",
      "nil",
      "private",
      "protected",
      "public",
      "return",
      "set",
      "static",
      "throw",
      "throws",
      "true",
      "false",
      "try",
      "val",
      "while",
  };
  if ((size_t)kind >= sizeof(names) / sizeof(names[0]))
    return "unknown token";
  return names[kind];
}
