# Eğer X# projesinde bu dosya olmazsa XS profilinde çalışır.
# XS profili aşağıdadır
# Başka key yoktur, value kısmına clang-format'tan bak.
# Yani key = value düşünürsek, key kısmına bir şey ekleme, value kısmına da clang-format'tan bak.

BasedOnStyle = "XS" # Aşağıdaki ayarlar XS profilinin varsayılanlarıdır. BasedOnStyle = "XS" yazmak ile aşağıdaki ayarları yazmak ayndır. Bu ayarlar XS profilinde değiştirilebilir. Örnek: BasedOnStyle = "Google", BreakBeforeBraces = "Allman"

[Indentation]
IndentWidth = 2
ContinuationIndentWidth = 4
BracedInitializerIndentWidth = -1
IndentCaseLabels = false
TabWidth = 2
PPIndentWidth = -1

[LineLength]
ColumnLimit = 120

[Braces]
BreakBeforeBraces = "Custom"
InsertBraces = false

[Braces.BraceWrappings]
AfterClass = true
AfterControlStatement = "Always"
AfterEnum = true
AfterFunction = true
AfterNamespace = true
AfterStruct = true
AfterUnion = true
BeforeCatch = true
BeforeElse = true
BeforeWhile = false
IndentBraces = false
SplitEmptyFunction = false
SplitEmptyRecord = true

[LineBreaking]
BreakAfterReturnType = "None"
BreakConstructorInitializers = "BeforeColon"
BreakStringLiterals = true
AlwaysBreakAfterDefinitionReturnType = "None"
AlwaysBreakBeforeMultilineStrings = false
AlwaysBreakTemplateDeclarations = "MultiLine"

[Penalties]
PenaltyBreakAssignment = 2
PenaltyBreakBeforeFirstCallParameter = 19
PenaltyBreakComment = 300
PenaltyBreakFirstLessLess = 120
PenaltyBreakString = 1000
PenaltyExcessCharacter = 1000000
PenaltyReturnTypeOnItsOwnLine = 60
PenaltyIndentedWhitespace = 0

[Alignment]
AlignAfterOpenBracket = "Align"
AlignEscapedNewlines = "Right"

[Alignment.AlignConsecutiveAssignments]
Enabled = false
AcrossEmptyLines = false
AcrossComments = false

[Alignment.AlignConsecutiveDeclarations]
Enabled = false

[Alignment.AlignOperands]
Enabled = true

[Alignment.AlignTrailingComments]
Kind = "Always"
OverEmptyLines = 0

[Spacing]
SpaceAfterLogicalNot = false
SpaceAfterTemplateKeyword = true
SpaceBeforeInheritanceColon = true
SpaceBeforeParens = "ControlStatements"
SpaceBeforeRangeBasedForLoopColon = true
SpaceBeforeSquareBrackets = false
SpaceInEmptyBlock = false
SpaceInEmptyParentheses = false
SpacesBeforeTrailingComments = 1
SpacesInAngles = "Never"
SpacesInConditionalStatement = false
SpacesInContainerLiterals = true
SpacesInLineComment = 1
SpacesInParentheses = false
SpacesInSquareBrackets = false

[Other]
AccessModifierOffset = -2
AllowAllParametersOfDeclarationOnNextLine = true
AllowShortBlocksOnASingleLine = "Never"
AllowShortCaseLabelsOnASingleLine = false
AllowShortEnumsOnASingleLine = false
AllowShortFunctionsOnASingleLine = "Empty"
AllowShortIfStatementsOnASingleLine = "Never"
AllowShortLambdasOnASingleLine = "All"
AllowShortLoopsOnASingleLine = false
QualifierAlignment = "Leave"
ReflowComments = "Always"
RemoveParentheses = "Leave"
SeparateDefinitionBlocks = "Leave"
ShortNamespaceLines = 1
SortUsingDeclarations = "LexicographicNumeric"
