accept-comment-above-attributes = true
accept-comment-above-statement = true

allow-comparison-to-zero = true
allow-dbg-in-tests = true
allow-exact-repetitions = true
allow-expect-in-consts = true
allow-expect-in-tests = true
allow-indexing-slicing-in-tests = true
allow-large-stack-frames-in-tests = true
allow-mixed-uninlined-format-args = true
allow-one-hash-in-raw-strings = false
allow-panic-in-tests = true
allow-print-in-tests = true
allow-private-module-inception = false
allow-renamed-params-for = [
    "core::convert::From",
    "core::convert::TryFrom",
    "core::str::FromStr",
]
allow-unwrap-in-consts = true
allow-unwrap-in-tests = true
allow-unwrap-types = []
allow-useless-vec-in-tests = true

allowed-dotfiles = []
allowed-duplicate-crates = []
allowed-idents-below-min-chars = ["i", "j", "k", "n", "r", "w", "x", "y", "z"]
allowed-prefixes = ["to", "as", "into", "from", "try_into", "try_from"]
allowed-scripts = ["Latin"]
allowed-wildcard-imports = ["prelude"]

arithmetic-side-effects-allowed = []
arithmetic-side-effects-allowed-binary = []
arithmetic-side-effects-allowed-unary = []

array-size-threshold = 16384
avoid-breaking-exported-api = true
await-holding-invalid-types = []

cargo-ignore-publish = false
check-grouped-late-init = true
check-incompatible-msrv-in-tests = false
check-inconsistent-struct-field-initializers = false
check-private-items = false

cognitive-complexity-threshold = 25
const-literal-digits-threshold = 30

disallowed-fields = []
disallowed-macros = []
disallowed-methods = []
disallowed-names = ["foo", "baz", "quux"]
disallowed-types = []

doc-valid-idents = [
    "API",
    "Arch",
    "CLI",
    "JSON",
    "Linux",
    "Picom",
    "Qtile",
    "TOML",
    "Wayland",
    "X11",
    "YAML",
    "..",
]

enable-raw-pointer-heuristic-for-send = true
enforce-iter-loop-reborrow = false
enforced-import-renames = []

enum-variant-name-threshold = 3
enum-variant-size-threshold = 200
excessive-nesting-threshold = 0
future-size-threshold = 16384

ignore-interior-mutability = ["bytes::Bytes"]
inherent-impl-lint-scope = "crate"

large-error-ignored = []
large-error-threshold = 128
lint-commented-code = false
literal-representation-threshold = 16384

matches-for-let-else = "WellKnownTypes"
max-fn-params-bools = 3
max-include-file-size = 1000000
max-struct-bools = 3
max-suggested-slice-pattern-length = 3
max-trait-bounds = 3
min-ident-chars-threshold = 1
missing-docs-allow-unused = false
missing-docs-in-crate-items = false

module-item-order-groupings = [
    [
        "modules",
        [
            "extern_crate",
            "mod",
            "foreign_mod",
        ],
    ],
    [
        "use",
        [
            "use",
        ],
    ],
    [
        "macros",
        [
            "macro",
        ],
    ],
    [
        "global_asm",
        [
            "global_asm",
        ],
    ],
    [
        "UPPER_SNAKE_CASE",
        [
            "static",
            "const",
        ],
    ],
    [
        "PascalCase",
        [
            "ty_alias",
            "enum",
            "struct",
            "union",
            "trait",
            "trait_alias",
            "impl",
        ],
    ],
    [
        "lower_snake_case",
        [
            "fn",
        ],
    ],
]
module-items-ordered-within-groupings = "none"

pass-by-value-size-limit = 256
pub-underscore-fields-behavior = "PubliclyExported"
recursive-self-in-type-definitions = true

semicolon-inside-block-ignore-singleline = false
semicolon-outside-block-ignore-multiline = false
single-char-binding-names-threshold = 4

source-item-ordering = ["enum", "impl", "module", "struct", "trait"]
stack-size-threshold = 512000

standard-macro-braces = [
    { name = "println", brace = "(" },
    { name = "eprintln", brace = "(" },
    { name = "format", brace = "(" },
    { name = "vec", brace = "[" },
    { name = "matches", brace = "(" },
]

struct-field-name-threshold = 3
suppress-restriction-lint-in-const = false

too-large-for-stack = 200
too-many-arguments-threshold = 7
too-many-lines-threshold = 100

trait-assoc-item-kinds-order = ["const", "type", "fn"]

type-complexity-threshold = 250
unnecessary-box-size = 128
unreadable-literal-lint-fractions = true
upper-case-acronyms-aggressive = false
vec-box-size-threshold = 4096
verbose-bit-mask-threshold = 1
warn-on-all-wildcard-imports = false
warn-unsafe-macro-metavars-in-private-macros = false
