# SPDX-FileCopyrightText: 2026 Leitwolf <xs-lang.chess031@slmails.com>
# SPDX-License-Identifier: MPL-2.0

edition = "2024"
style_edition = "2024"
unstable_features = true
required_version = "*"

max_width = 120
hard_tabs = false
tab_spaces = 2
newline_style = "Unix"
use_small_heuristics = "Default"
fn_call_width = 72
attr_fn_like_width = 84
struct_lit_width = 22
struct_variant_width = 42
array_width = 72
chain_width = 72
single_line_if_else_max_width = 0
single_line_let_else_max_width = 0
short_array_element_width_threshold = 10

brace_style = "AlwaysNextLine"
control_brace_style = "AlwaysNextLine"
empty_item_single_line = true
fn_single_line = false
where_single_line = false
struct_lit_single_line = false
indent_style = "Visual"

fn_params_layout = "Tall"
binop_separator = "Back"
combine_control_expr = true
overflow_delimited_expr = true
force_multiline_blocks = false
format_strings = true
trailing_comma = "Vertical"
trailing_semicolon = true
match_block_trailing_comma = false
match_arm_blocks = true
match_arm_leading_pipes = "Never"
match_arm_indent = true

reorder_imports = true
reorder_modules = true
reorder_impl_items = false
imports_granularity = "Preserve"
group_imports = "Preserve"
imports_indent = "Block"
imports_layout = "Mixed"
merge_derives = true
force_explicit_abi = true
remove_nested_parens = true
use_try_shorthand = false
use_field_init_shorthand = false
condense_wildcard_suffixes = false

space_before_colon = false
space_after_colon = true
spaces_around_ranges = false
type_punctuation_density = "Wide"

struct_field_align_threshold = 0
enum_discrim_align_threshold = 0
inline_attribute_width = 0

blank_lines_lower_bound = 0
blank_lines_upper_bound = 1
wrap_comments = true
comment_width = 120
normalize_comments = false
normalize_doc_attributes = false
format_code_in_doc_comments = false
doc_comment_code_block_width = 120
format_generated_files = true
generated_marker_line_search_limit = 5

hex_literal_case = "Preserve"
float_literal_trailing_zero = "Preserve"

color = "Auto"
disable_all_formatting = false
show_parse_errors = true
error_on_line_overflow = false
error_on_unformatted = false
ignore = []
skip_children = false
