# SPDX-FileCopyrightText: 2026 Leitwolf <xs-lang.chess031@slmails.com>
# SPDX-License-Identifier: Apache-2.0

include_guard(GLOBAL)

if(DEFINED CMAKE_C_COMPILER)
  get_filename_component(XS_REQUESTED_C_COMPILER "${CMAKE_C_COMPILER}" NAME)
  if(XS_REQUESTED_C_COMPILER MATCHES "^(gcc|g\\+\\+|cc)(-[0-9]+)?$")
    message(FATAL_ERROR "GNU compiler driver '${XS_REQUESTED_C_COMPILER}' is unsupported; use Clang.")
  endif()
endif()

find_program(XS_CLANG_EXECUTABLE NAMES clang REQUIRED)
find_program(XS_LLVM_AR_EXECUTABLE NAMES llvm-ar REQUIRED)
find_program(XS_LLVM_RANLIB_EXECUTABLE NAMES llvm-ranlib REQUIRED)
find_program(XS_LLVM_NM_EXECUTABLE NAMES llvm-nm REQUIRED)
find_program(XS_LLVM_OBJCOPY_EXECUTABLE NAMES llvm-objcopy REQUIRED)
find_program(XS_LLVM_OBJDUMP_EXECUTABLE NAMES llvm-objdump REQUIRED)
find_program(XS_LLVM_STRIP_EXECUTABLE NAMES llvm-strip REQUIRED)
find_program(XS_LLD_EXECUTABLE NAMES ld.lld REQUIRED)

function(xs_require_tool_basename variable expected)
  get_filename_component(tool_name "${${variable}}" NAME)
  if(NOT tool_name STREQUAL "${expected}")
    message(FATAL_ERROR "GNU-compatible fallback tool '${tool_name}' is unsupported; expected '${expected}'.")
  endif()
endfunction()

function(xs_require_tool_identity variable identity)
  execute_process(COMMAND "${${variable}}" --version
                  RESULT_VARIABLE version_status
                  OUTPUT_VARIABLE version_output
                  ERROR_VARIABLE version_error
                  OUTPUT_STRIP_TRAILING_WHITESPACE
                  ERROR_STRIP_TRAILING_WHITESPACE)
  if(NOT version_status EQUAL 0 OR NOT "${version_output}\n${version_error}" MATCHES "${identity}")
    message(FATAL_ERROR "Tool '${${variable}}' does not identify itself as ${identity}.")
  endif()
endfunction()

xs_require_tool_basename(XS_LLVM_AR_EXECUTABLE llvm-ar)
xs_require_tool_basename(XS_LLVM_RANLIB_EXECUTABLE llvm-ranlib)
xs_require_tool_basename(XS_LLVM_NM_EXECUTABLE llvm-nm)
xs_require_tool_basename(XS_LLVM_OBJCOPY_EXECUTABLE llvm-objcopy)
xs_require_tool_basename(XS_LLVM_OBJDUMP_EXECUTABLE llvm-objdump)
xs_require_tool_basename(XS_LLVM_STRIP_EXECUTABLE llvm-strip)
xs_require_tool_basename(XS_LLD_EXECUTABLE ld.lld)
xs_require_tool_identity(XS_LLVM_AR_EXECUTABLE LLVM)
xs_require_tool_identity(XS_LLVM_RANLIB_EXECUTABLE LLVM)
xs_require_tool_identity(XS_LLVM_NM_EXECUTABLE LLVM)
xs_require_tool_identity(XS_LLVM_OBJCOPY_EXECUTABLE LLVM)
xs_require_tool_identity(XS_LLVM_OBJDUMP_EXECUTABLE LLVM)
xs_require_tool_identity(XS_LLVM_STRIP_EXECUTABLE LLVM)
xs_require_tool_identity(XS_LLD_EXECUTABLE LLD)

set(CMAKE_C_COMPILER "${XS_CLANG_EXECUTABLE}" CACHE FILEPATH "Clang C compiler" FORCE)
set(CMAKE_AR "${XS_LLVM_AR_EXECUTABLE}" CACHE FILEPATH "LLVM archiver" FORCE)
set(CMAKE_RANLIB "${XS_LLVM_RANLIB_EXECUTABLE}" CACHE FILEPATH "LLVM archive indexer" FORCE)
set(CMAKE_NM "${XS_LLVM_NM_EXECUTABLE}" CACHE FILEPATH "LLVM symbol tool" FORCE)
set(CMAKE_OBJCOPY "${XS_LLVM_OBJCOPY_EXECUTABLE}" CACHE FILEPATH "LLVM object copier" FORCE)
set(CMAKE_OBJDUMP "${XS_LLVM_OBJDUMP_EXECUTABLE}" CACHE FILEPATH "LLVM object dumper" FORCE)
set(CMAKE_STRIP "${XS_LLVM_STRIP_EXECUTABLE}" CACHE FILEPATH "LLVM strip tool" FORCE)
set(CMAKE_LINKER "${XS_LLD_EXECUTABLE}" CACHE FILEPATH "LLVM linker" FORCE)
set(CMAKE_C_COMPILER_AR "${XS_LLVM_AR_EXECUTABLE}" CACHE FILEPATH "Clang archiver" FORCE)
set(CMAKE_C_COMPILER_RANLIB "${XS_LLVM_RANLIB_EXECUTABLE}" CACHE FILEPATH "Clang archive indexer" FORCE)

function(xs_validate_llvm_toolchain)
  if(CMAKE_C_COMPILER_ID STREQUAL "GNU")
    message(FATAL_ERROR "The X# compiler does not support GCC; the selected clang command resolves to GNU C.")
  endif()
  get_filename_component(compiler_name "${CMAKE_C_COMPILER}" NAME)
  if(NOT compiler_name MATCHES "^clang(-[0-9]+)?$")
    message(FATAL_ERROR "Compiler driver '${compiler_name}' is unsupported; use Clang.")
  endif()
  if(NOT CMAKE_C_COMPILER_ID MATCHES "Clang")
    message(FATAL_ERROR "The X# compiler requires Clang.")
  endif()
  if(NOT CMAKE_GENERATOR MATCHES "^Ninja")
    message(FATAL_ERROR "The X# compiler requires Ninja; GNU Make and other generators are unsupported.")
  endif()
  if(CMAKE_C_FLAGS MATCHES "(^| )-std=gnu" OR CMAKE_C_FLAGS_DEBUG MATCHES "(^| )-std=gnu" OR
     CMAKE_C_FLAGS_RELEASE MATCHES "(^| )-std=gnu")
    message(FATAL_ERROR "GNU C dialect flags are unsupported; use strict C23.")
  endif()
  add_link_options(-fuse-ld=lld)
endfunction()
